[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[scrolling]
multiplier = 5

[selection]
save_to_clipboard = true

[window]
opacity = 0.9

[window.padding]
x = 15
y = 15

[general]
import = [
    "~/.config/alacritty/catppuccin_macchiato.toml"
]